# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0020_auto_20170815_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekfile',
            name='file',
        ),
    ]
