# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0021_remove_ekfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekfile',
            name='file',
            field=models.FileField(default='/var', upload_to=b''),
            preserve_default=False,
        ),
    ]
